### ISSUE TITLE
model_word_document.pkl 不存在

### ISSUE THREAD

**Issue by llxgithub** [renjunxiang/chatbot_by_similarity#2]
您好，我从github里面下载了您的chatbot_by_similarity，但是在运行代码时该文件model_word_document.pkl 不存在，可以提供下吗，我的qq是2772595852，谢谢哈

**Comment by renjunxiang** [comment]
你好，运行demo_train_knowledge.py，会保存文档的句向量，生成model_word_document.pkl 作为后续相似度计算的数据
